"""
Django settings for clarusway project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent   # bizim projemizin yolu __dirname__ gibi


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=7hv7)bq$okj490i_^v1u&(i-wosxy&ct+i32%#78_hpw7$b3a' # bu sifre burada olmayacak .env gibi sakli tutulacak

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # development durumunda hata ayaklamasi yapabilmek icin, canli da false yapilcak

ALLOWED_HOSTS = []  # host olarak aldigimiz adresler buraya yazilacak, sadec o hosta calisir.


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin', #
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions', # web sayfasinin kullanici bilgilerini hafiza da tutmasini sagliyor, cookie leri kullaniyor
    'django.contrib.messages', # bildirimler icin
    'django.contrib.staticfiles',
    'firstapp.apps.FirstappConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware', # koruma icin
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware', 
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware', # 
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'clarusway.urls' # ana url dosyasini gosteriyor. ana router gibi

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates', # burada kullanilacak template belirtilir
        'DIRS': [], # template dosyasinin yolu yazilir. egerfarkli bir yerde olusturulmussa
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'clarusway.wsgi.application' # web server ile frame workun baglantisini sagliyor, burada yolu gosteriyor


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = { # default olarak sqlite3 geliyor ama buraya istenilen database eklenebilir
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [ 
    {    # password ile kullanici bilgilerini karsilastiryor, benzerse hata veriyor
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', 
    },
    {   # en az 8 karakter olacak onu kontrol ediyor.
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {   # kendi hafizasinde cok kullanilan sifreler var, onlar olursa hata veriyor
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {   # sifrenin tamami rakamlardan olusursa hata veriyor
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us' # uyari dilleri ayarlaniyor, turkcede olabilir. 

TIME_ZONE = 'UTC' # timezone ayarlamak icin

USE_I18N = True # multi language icin bu kisim true olacak

USE_L10N = True # lokalizasyon kulanilmasi icin, usa de tarih farkli yaziliyor, tr de farkli onun gibi

USE_TZ = True # timezone icin true olacak


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
